[project]
authors = [
  {email = "engineering@canvasmedical.com", name = "Canvas Team"}
]
dependencies = [
  "canvas[test-utils]",
  "pytest-cov>=7.0.0",
]
description = "Some description of your project."
license = "MIT"
name = "preventive-care-tracker"
readme = "preventive_care_tracker/README.md"
requires-python = ">=3.11"
version = "0.1.0"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
preventive_care_tracker = ["*.png"]

[tool.pytest.ini_options]
python_files = ["*_tests.py", "test_*.py", "tests.py"]
